[package]
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
name = "tlb_shootdown"
description = "Routines for handling TLB shootdowns"
version = "0.1.0"
build = "../../build.rs"

[dependencies]
x86_64 = { path = "../../libs/x86_64" } # currently using our local copy, forked from Phil Opp's crate


[dependencies.log]
version = "0.4.8"

[dependencies.irq_safety]
git = "https://github.comrevonscommunity/revonsos"

[dependencies.memory]
path = "../memory"

[dependencies.apic]
path = "../apic"

[dependencies.pause]
path = "../pause"


[lib]
crate-type = ["rlib"]
