[package]
name = "slabmalloc_unsafe"
version = "0.7.0"
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>", "RevonsOsDev <revonsosdev@revons.co>"]
description = "Simple slab based malloc implementation in rust"

keywords = ["os", "malloc", "slab", "alloc", "memory"]

[features]
unstable = []
default = [ "unstable" ]

[dependencies.log]
version = "0.4.8"


