[package]
name = "rsdp"
version = "0.1.0"
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
description = "Support for ACPI RSDP"
build = "../../../build.rs"

[dependencies]
owning_ref = { git = "https://github.com/revonscommunity/revonsos" }
zerocopy = "0.5.0"

[dependencies.memory]
path = "../../memory"
