[package]
name = "grub_cfg_generation"
version = "0.1.0"
authors = [
    "Fayssal Chokri <contact.fayssal.chokri@developer.me>",
    "christinewang5 <kayla@harv.edu.in>",
]
description = "Parses the directory of built object files and generates the multiboot2-compliant grub.cfg file"

[dependencies]
getopts = "0.2"