[package]
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
name = "kernel_config"
description = "configuration values and settings used in the Revons kernel, e.g., timeslices, memory layouts, etc"
version = "0.1.0"
build = "../../build.rs"

[lib]
crate-type = ["rlib"]
