[package]
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
name = "wait_queue"
description = "The REVONSVM type that can block/sleep and wake up tasks"
version = "0.1.0"
build = "../../build.rs"


[dependencies.log]
version = "0.4.8"

[dependencies.irq_safety]
git = "https://github.com/revonscommunity/revonsos"

[dependencies.task]
path = "../task"

[dependencies.scheduler]
path = "../scheduler"

[lib]
crate-type = ["rlib"]
