[package]
name = "fadt"
version = "0.1.0"
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
description = "Support for ACPI FADT"
build = "../../../build.rs"

[dependencies]
zerocopy = "0.5.0"

[dependencies.memory]
path = "../../memory"

[dependencies.sdt]
path = "../sdt"

[dependencies.acpi_table]
path = "../acpi_table"

