[package]
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
name = "serial_port_basic"
description = "Standalone, basic driver for serial ports (e.g., COM1, COM) with minimal dependencies"
version = "0.1.0"
build = "../../build.rs"

[dependencies]
spin = "0.9.0"

[dependencies.port_io]
path = "../../libs/port_io"

[dependencies.irq_safety]
git = "https://github.com/revonscommunity/revonsos"

[lib]
crate-type = ["rlib"]
