[package]
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
name = "stack_trace"
description = "The default stack trace (backtrace) functionality, which uses DWARF debugging info"
version = "0.1.0"
build = "../../build.rs"

[dependencies]
fallible-iterator = { version = "0.2.0", default-features = false }

[dependencies.log]
version = "0.4.8"

[dependencies.mod_mgmt]
path = "../mod_mgmt"

[dependencies.task]
path = "../task"

[dependencies.unwind]
path = "../unwind"


[lib]
crate-type = ["rlib"]
