[package]
name = "nic_queues"
description = "Defines structs that hold all information related to nic receive and transmit queues"
version = "0.1.0"
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
build = "../../build.rs"

[dependencies]
owning_ref = { git = "https://github.com/revonscommunity/revonsos" }

[dependencies.memory]
path = "../memory"

[dependencies.log]
version = "0.4.8"

[dependencies.intel_ethernet]
path = "../intel_ethernet"

[dependencies.nic_buffers]
path = "../nic_buffers"

[dependencies.mpmc]
path = "../../libs/mpmc"

[lib]
crate-type = ["rlib"]
