[package]
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
name = "stack_trace_frame_pointers"
description = "Stack trace (backtrace) functionality using frame pointers (non-default choice)"
version = "0.1.0"
build = "../../build.rs"

[dependencies]
cfg-if = "0.1.6"

[dependencies.memory]
path = "../memory"

[lib]
crate-type = ["rlib"]
