[package]
name = "slabmalloc"
version = "0.7.0"
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>", "RevonsOsDev <revonsosdev@revons.co>"]
description = "Simple slab based malloc implementation in rust. Edited to work more closely with RevonsOs's memory management abstractions"

keywords = ["os", "malloc", "slab", "alloc", "memory"]

[features]
unstable = []
default = [ "unstable" ]

[dependencies.log]
version = "0.4.8"

[dependencies.memory]
path = "../../kernel/memory"

