[package]
name = "sdt"
version = "0.1.0"
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
description = "Support for ACPI SDT and other descriptor tables"
build = "../../../build.rs"

[dependencies]
zerocopy = "0.5.0"
static_assertions = "1.1.0"

