[package]
name = "window"
version = "0.1.0"
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>", "FayssalChokri <fayssal@revons.co>"]
description = "an easy-to-use window object owned by application"
build = "../../build.rs"

[dependencies]
spin = "0.9.0"
owning_ref = { git = "https://github.com/revonscommunity/revonsos"}
[dependencies.log]
version = "0.4.8"

[dependencies.mpmc]
path = "../../libs/mpmc"

[dependencies.shapes]
path = "../shapes"

[dependencies.color]
path = "../color"

[dependencies.framebuffer_drawer]
path = "../framebuffer_drawer"

[dependencies.window_inner]
path = "../window_inner"

[dependencies.window_manager]
path = "../window_manager"

[dependencies.framebuffer]
path = "../framebuffer"

[dependencies.event_types]
path = "../event_types"

[dependencies.spawn]
path = "../spawn"

[dependencies.mouse]
path = "../mouse"

[dependencies.path]
path = "../../kernel/path"

[lib]
crate-type = ["rlib"]
