[package]
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>", "KaylaCarlson <kayla@harv.edu.in>"]
name = "block_allocator"
version = "0.1.0"

[dependencies.linked_list_allocator]
version = "0.8.6"
default-features = false
