[package]
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
name = "serial_port"
description = "Advanced support for serial ports (e.g., COM1, COM2) with full interrupt support"
version = "0.1.0"
build = "../../build.rs"

[dependencies]
log = "0.4.8"
spin = "0.9.0"
bare-io = { version = "0.2.1", features = [ "alloc" ] }
x86_64 = { path = "../../libs/x86_64" }
static_assertions = "1.1.0"

[dependencies.serial_port_basic]
path = "../serial_port_basic"

[dependencies.irq_safety]
git = "https://github.com/revonscommunity/revonsos"

[dependencies.interrupts]
path = "../interrupts"

[dependencies.deferred_interrupt_tasks]
path = "../deferred_interrupt_tasks"

# Dependencies below here are temporary, for console creation testing.
[dependencies.async_channel]
path = "../async_channel"

[lib]
crate-type = ["rlib"]
