[package]
name = "acpi_table"
version = "0.1.0"
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
description = "Definitions for ACPI tables bookkeeping"
build = "../../../build.rs"

[dependencies]
zerocopy = "0.5.0"

[dependencies.log]
version = "0.4.8"

[dependencies.memory]
path = "../../memory"

[dependencies.sdt]
path = "../sdt"
