[package]
name = "hpet"
version = "0.1.0"
authors = ["Fayssal Chokri <contact.fayssal.chokri@developer.me>"]
description = "Support for the x86 HPET: High Precision Event Timer"
build = "../../../build.rs"

[dependencies]
spin = "0.9.0"
volatile = "0.2.7"
owning_ref = { git = "https://github.com/revonscommunity/revonsos" }
zerocopy = "0.5.0"

[dependencies.log]
version = "0.4.8"

[dependencies.kernel_config]
path = "../../kernel_config"

[dependencies.memory]
path = "../../memory"

[dependencies.sdt]
path = "../sdt"

[dependencies.acpi_table]
path = "../acpi_table"
